### ISSUE TITLE
How to interface multiple pins?

### ISSUE THREAD

**Issue by petit-miner** [halherta/RaspberryPi-i2c8Bit#1]
Hey there,
I'm struggling to read multiple pins and differentiate between them.
Could you please help me?

**Comment by halherta** [comment]
Marcel,
Have a look at this article (it got moved around and the url
changed...sorry!).
http://www.hertaville.com/interfacing-an-i2c-gpio-expander-mcp23017-to-the-raspberry-pi-using-c.html
Hopefully it should fill you in on some details...basically the MCP23017
has two ports called GPIOA and GPIOB.
The state of the pins on each port is controllable by several
registers...for example the IODIRA (8-bit) register whose internal address
is 0x00, controls whether the GPIOA port pins are output or input. Each bit
in that register controls one pin so for example if I write the value
0b11110000 into the IODIRA register, I'm going to make physical pins GPA0-3
outputs and pins GPA4-7 inputs. if I write the value 0b10101010 into the
IODIRA register, I'm going to make physical pins GPA0,2,4,6 outputs and
pins GPA1,3,5,7 inputs. Writing a '1' in the nth bit in the IODIRA register
makes the GPAnth pin an input.Writing a '0' in the nth bit in the IODIRA
register makes the GPAnth pin an output.

If the nth pin is an output, I can then set it to output high or low as
follows:
Writing a 1 in the nth bit in the OLATA (0x14) register makes the GPAnth
pin an output high
Writing a 0 in the nth bit in the OLATA (0x14) register makes the GPAnth
pin an output low

If the nth pin is an input pin, I can read its state by reading the value
of the nth bit in the GPIOA (0x12) register

If I read a '1' the pin is HIGH if I read a '0' then the pin is LOW.

to lets say set pins GPA0-3 to outputs and GPA4-7 to inputs I could do the
following:

//instantiate i2c8Bit object called mcp23017//specify a device address
0x20 and i2c device "/dev/i2c-1"

//0b00100000 -> 0010 0000 -> 0x20

i2c8Bit mcp23017(0b00100000,string("/dev/i2c-1"));

// here the first parameter is for the address of the register that I
want to write to...in this case address 0x00 is that of the OLATA
register

//The second parameter is the value to write into the OLATA register
in binary as denoted by '0b'  '0b11110000' will make GPA0-3 outputs
and GPA4-7 inputs

 mcp23017.writeReg(0x00,0b11110000);

To make pins GPA0,2 output HIGHS and GPA1,3 output LOWS

//write to the OLATA register
mcp23017.writeReg(0x14,0b00000101);

To read the state of the GPA7 input pin, read from the GPIOA(0x12)
register and bitwise AND it with a mask with a '1' in the seventh
position i.e.0b10000000. If the result of this operation is non-zero,
then the GPA7 pin is high else it was low.

To read the state of the GPA5 input pin, read from the GPIOA(0x12)
register and bitwise AND it with a mask with a '1' in the fifth
position  i.e.0b00100000. If the result of this operation is non-zero,
then the GPA7 pin is high else it was low.



unsigned char pinStatus = 0;

//read the GPIOA register..save value in variable pin status

mcp23017.readReg(0x12,pinStatus);

if(pinStatus & 0b1000000){

cout << "GPA7 PIN STATE IS HIGH" << endl;

}else{

cout << "GPA7 PIN STATE IS LOW" << endl;
}


if(pinStatus & 0b0010000){

cout << "GPA5 PIN STATE IS HIGH" << endl;

}else{

cout << "GPA5 PIN STATE IS LOW" << endl;
}


Hope this helps. Please also refer to the datasheet of the MCP23017 as
well. goodluck!


Hussam

**Comment by petit-miner** [comment]
Thank you 
My Program is now working without any issues.
